--- #YAML:1.0
name:               Net-NTP
version:            1.3
abstract:           Perl extension for decoding NTP server responses
author:
    - Ask Bjørn Hansen <ask@develooper.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
